services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Parthenon\Notification\EmailSenderInterface: '@Parthenon\Notification\Sender\NullEmailSender'